// 1. Generate number between 0-2.
// 2. Use that number to select from rpsArr.


let rpsArr = ["rock", "paper", "scissors"];
// Array holding the possible selections


let randomNum = (max) => {
  return Math.floor(Math.random() * max);
}
// Math.random generates a number between 0 and less than 1 (O is inclusive while 1 is exclusive). Then we multiply that by our max number, which we'll always set to 3. We have all that inside of our Math.floor function which will return the largest integer less than or equal to a given number. 

//  For example, Math.random could generate something like .05741. Then it gets immediately multiplied by 3 which would give us 0.17223. This number is then passed into the Math.floor function which rounds it down to the nearest integer, which is 0.


let computerPlay = () => {
  return rpsArr[randomNum(3)];
}
// This is the main function that will be used to generate the computers selection of either rock, paper, or scissors. 

// In this function, we are returning an element from our array named rpsArr. To do this we use bracket notation. However, instead of us hard coding a number in the brackets, we pass the function randomNum(3)

// Notice, we're using bracket notation to access an element in our array named rpsArray. We use the randomNum function with 3 passed as the argument. This will generate 0, 1, or 2. Whichever number is generated by randomNum(3) will be the element in rpsArr that our function returns.





function playRound(playerSelection, computerSelection) {
  // your code here!
}

const playerSelection = "rock";
const computerSelection = computerPlay();

